Add bower.json
webcomponents/template pull request #12
Opened 2017-03-10 08:19 UTC by FluorescentHallucinogen

Not sure about package name. Currently `template` in Bower points to https://github.com/jgallen23/template. What about renaming `template` to `html-template` and use the same package name in Bower and NPM? ;)

2017-03-24 06:57 UTC, FluorescentHallucinogen commented
@webcomponents, anybody please merge this pull request.

2017-03-27 21:52 UTC, notwaldorf requested changes

2017-03-27 21:52 UTC, notwaldorf commented on bower.json
> +  "name": "html-template",
Just call it `template`. This won't be published to the bower catalog, so the name doesn't matter for uniqueness

2017-03-27 21:52 UTC, notwaldorf commented on bower.json
> +  "description": "HTML Template polyfill",
Please use the same description as in package.json

2017-03-27 21:52 UTC, notwaldorf commented on bower.json
> +    "**/.*",
Why is this generic wildcard needed?

2017-03-28 07:30 UTC, FluorescentHallucinogen commented on bower.json
> +    "**/.*",
It's needed for excluding files like `.travis.yml`, `.gitignore`, etc. from Bower package.

2017-04-14 12:56 UTC, FluorescentHallucinogen commented
All requested changes done.
@notwaldorf, @azakus, @bicknellr, @sorvell, @justinfagnani, please merge this pull request.

2017-05-12 07:57 UTC, FluorescentHallucinogen commented
@notwaldorf, @azakus, @bicknellr, @sorvell, @justinfagnani PTAL.

2018-03-07 01:36 UTC, notwaldorf commented
Closing since this is a very old PR and needs a rebase

2018-03-07 01:36 UTC, closed without merging