Update package.json
webcomponents/template pull request #13
Opened 2017-03-13 12:48 UTC by FluorescentHallucinogen

2017-03-24 06:57 UTC, FluorescentHallucinogen commented
@webcomponents, anybody please merge this pull request.

2017-03-27 21:50 UTC, notwaldorf requested changes

2017-03-27 21:50 UTC, notwaldorf commented on package.json
> +  "description": "HTML Template polyfill",
Why the change? The original description says exactly what this does

2017-03-27 21:50 UTC, notwaldorf commented on package.json
> +  "description": "HTML Template polyfill",
Also needs a rebase

2017-03-27 22:20 UTC, notwaldorf commented on package.json
> +  "author": "The Polymer Project Authors (https://polymer.github.io/AUTHORS.txt)",
Also, as mentioned in many of the other PRs, pls don't make this change

2017-03-28 07:18 UTC, FluorescentHallucinogen commented on package.json
> +  "description": "HTML Template polyfill",
Is it possible to use this project as separate HTML Template polyfill without webcomponents.js? If yes, what difference does it make which project uses it?

2017-03-28 07:23 UTC, FluorescentHallucinogen commented on package.json
> +  "author": "The Polymer Project Authors (https://polymer.github.io/AUTHORS.txt)",
I agree with changing "Polymer Project Authors" to "Polymer Authors", but what's wrong with using URL to authors list in `bower.json`/`package.json`?

@azakus, WDYT?

2017-04-14 12:56 UTC, FluorescentHallucinogen commented
All requested changes done.
@notwaldorf, @azakus, @bicknellr, @sorvell, @justinfagnani, please merge this pull request.

2017-05-12 07:56 UTC, FluorescentHallucinogen commented
@notwaldorf, @azakus, @bicknellr, @sorvell, @justinfagnani PTAL.

2018-03-07 01:36 UTC, notwaldorf commented
Closing, since this is a very old PR and needs a rebase

2018-03-07 01:36 UTC, closed without merging